import fs from 'node:fs';
import path from 'node:path';
const dir = path.dirname(new URL(import.meta.url).pathname);
const esc = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const ledger = fs.readFileSync(path.join(dir,'sources-ledger.md'),'utf8');
const sources = [...ledger.matchAll(/^\[S(\d+)\] (https?:\/\/\S+) — (.+)$/gm)].map(m=>({id:m[1],url:m[2],description:m[3]}));
fs.mkdirSync(path.join(dir,'assets'),{recursive:true});
const svgHead = (title,w,h)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img"><title>${title}</title><style>text{font-family:'Noto Sans CJK KR',sans-serif;fill:#17212B;font-size:17px}.small{font-size:14px;fill:#5D6770}.head{font-size:21px;font-weight:700}rect{fill:#F8F7F3;stroke:#D6D3CA}line,path{stroke:#0B6E69;fill:none;stroke-width:2}</style>`;
const timeline = [
 ['2000','설립 연도라는 당사자 설명','부분 확인 [S3]'],
 ['2010','Ardmore 제조 사실관계','법원 기록 [S20]'],
 ['2013','Millwood 공장 계획 발표','주정부 배포문 [S12]'],
 ['2017','한국 투자협약 기록','GFEZ 연혁 [S18]'],
 ['2022','미가동 설비 공매 예고','경매업체 기고 [S15]'],
 ['2026','현재 도메인 별도 식별','Carbonyx Minerals [S16]']
 ];
const timelineSvg=svgHead('공개 기록의 주요 시점',850,440)+`<text x="28" y="35" class="head">공개 기록의 주요 시점</text><text x="28" y="62" class="small">연도별 사건 배열 · 간격은 시간 비례가 아님</text><line x1="95" y1="90" x2="95" y2="390"/>`+timeline.map((r,i)=>{const y=102+i*57;return `<circle cx="95" cy="${y}" r="6" fill="#0B6E69"/><text x="28" y="${y+6}">${r[0]}</text><text x="125" y="${y+1}">${r[1]}</text><text x="125" y="${y+23}" class="small">${r[2]}</text>`}).join('')+'</svg>';
const relationSvg=svgHead('명칭과 증거의 연결',850,440)+`<text x="25" y="34" class="head">명칭과 증거의 연결</text><rect x="25" y="65" width="245" height="70"/><text x="42" y="94">CBNX ASIA</text><text x="42" y="119" class="small">대표·JV 관계를 자칭 [S1,S7]</text><rect x="535" y="65" width="285" height="70"/><text x="550" y="94">CBNX GROUP LLC</text><text x="550" y="119" class="small">법적 승계 확인 필요 [S3]</text><line x1="270" y1="100" x2="535" y2="100" stroke-dasharray="7 5"/><text x="315" y="87" class="small">웹사이트의 관계 설명</text><rect x="25" y="203" width="245" height="90"/><text x="42" y="231">Carbonyx Inc.</text><text x="42" y="256" class="small">법원: Ardmore 제조</text><text x="42" y="279" class="small">[S8,S20]</text><rect x="293" y="203" width="245" height="90"/><text x="310" y="231">Carbonyx International</text><text x="310" y="256" class="small">GFEZ 투자협약 당사자 명칭</text><text x="310" y="279" class="small">[S18] · Inc. 동일성 미확인</text><rect x="560" y="203" width="260" height="90"/><text x="574" y="231">Carbonyx International</text><text x="574" y="254">USA, Inc.</text><text x="574" y="279" class="small">SEC 발행인 [S10]</text><text x="25" y="177" class="small">아래 명칭들은 개별 식별 대상이다. 서로의 지분·승계 연결선은 확정하지 않는다.</text><rect x="25" y="332" width="795" height="70"/><text x="42" y="360">현재 carbonyx.com: Carbonyx Minerals Inc. [S16,S17]</text><text x="42" y="385" class="small">Vancouver 사업자 소개를 역사적 Texas Carbonyx에 합산하지 않음</text><text x="25" y="430" class="small">범례: 점선 = 당사자 주장 · 상자 = 기록에서 구별되는 명칭 · 지분 관계도 아님</text></svg>`;
fs.writeFileSync(path.join(dir,'assets/timeline.svg'),timelineSvg);
fs.writeFileSync(path.join(dir,'assets/relationship.svg'),relationSvg);
const figure=(name,title,caption)=>`<figure><div class="figure-frame"><img src="assets/${name}.svg" alt="${title}"></div><figcaption>${caption}</figcaption></figure>`;
const table=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const pages=[];
pages.push(`<p class="kicker">공개자료 실사 보고서 · 기준일 2026-10-04</p><h1>CBNX와 Carbonyx<br>관계와 사업 이력</h1><p class="lead">공개적인 사업 연계 설명은 확인된다.<br>법적 승계와 계약 범위는 확정되지 않는다.</p><p>CBNX ASIA는 현재 미국 CBNX GROUP의 아시아 독점 대표라고 소개하며, 과거 페이지에서는 Carbonyx의 아시아 JV 파트너라는 표현을 사용했다. 이는 당사자가 공개한 관계 설명의 존재를 확인하는 근거다. 독점권의 범위, 계약 기간, 지분 및 합작법인의 실재를 입증하는 계약서는 확보되지 않았다. [S1][S3][S7]</p><p>역사적 Carbonyx의 제조 활동과 한국 투자협의에는 법원 및 정부 기록이 있다. 그러나 이 기록이 오늘의 CBNX GROUP LLC에 대한 소유권이나 자산 승계를 보증하지 않는다. Carbonyx Inc., Carbonyx International Inc., Carbonyx International USA, Inc.를 하나의 법인으로 합치면 안 된다. [S8][S10][S18][S20]</p><h2>의사결정에 필요한 판정</h2>${table(['쟁점','현재 판정'],[
['아시아 대표·JV 관계','공개 주장 확인. 계약상 권리와 지분은 미확인. [S1][S7]'],
['CBNX의 법적 후신 여부','웹사이트의 전신 설명은 있으나 법인 변경·자산 양도 연결은 미확인. [S3][S13]'],
['과거 제조와 한국 활동','Ardmore 제조 사실관계와 GFEZ 투자협약 기록이 존재. [S18][S20]'],
['Millwood 사업 결과','정부 계획 발표와 경매업체의 미가동 설비 설명을 구분해야 함. [S12][S15]'],
['현재 carbonyx.com','Carbonyx Minerals 소개를 역사적 Texas 사업에 합산하지 않음. [S16][S17]']])}<p class="note">읽는 법: ‘확인’은 해당 문서가 명시하는 범위만 뜻한다. ‘부분 확인’은 당사자 설명 또는 간접 단서의 존재를 뜻하며, ‘미확인’은 사실 부정이 아니라 근거 부족을 뜻한다.</p>`);
pages.push(`<p class="kicker">식별과 관계</p><h2>명칭을 분리해야 관계가 보인다</h2>${figure('relationship','명칭과 증거의 연결','그림: 명칭·근거 지도. 선은 웹사이트의 관계 설명만 나타내며 지분 또는 법적 승계를 뜻하지 않는다. [S1][S3][S7][S8][S10][S16][S17][S18][S20]')}<h3>CBNX ASIA와 CBNX GROUP</h3><p>현행 CBNX ASIA 소개는 배승호를 CBNX ASIA CEO로, Siddhartha Gaur를 CBNX GROUP CEO로 표시한다. 그룹 소개는 CBNX GROUP LLC를 과거 Carbonyx International Inc.라고 설명한다. 같은 도메인에 있는 여러 페이지는 독립적인 교차 검증 자료로 세지 않았다. [S1][S3]</p><h3>동일 인물과 유사 명칭의 한계</h3><p>법원 의견의 Carbonyx Inc.와 SEC의 Carbonyx International USA, Inc.에 Siddhartha Gaur라는 인물이 등장한다. 이는 연계 조사의 단서지만 동일 법인, 모자회사 또는 후신 관계를 확정하는 증거는 아니다. GFEZ에 기재된 Carbonyx International 역시 별도의 식별 대상이다. [S8][S10][S18]</p><h3>도메인은 시점을 붙여 읽는다</h3><p>과거 carbonyx.com 아카이브는 CASP·Cokonyx와 Texas·Ardmore 사업을 소개했다. 현재 동일 도메인은 Vancouver의 Carbonyx Minerals Inc.를 소개하며 UBC 벤처 프로필에도 이 명칭이 나타난다. 도메인 문자열만 같다는 이유로 과거 기술·프로젝트를 현재 사업자의 실적으로 옮기지 않았다. [S5][S16][S17]</p>`);
const chronology=[
['2000','Siddhartha Gaur가 Carbonyx를 설립했다는 그룹 소개.','부분: 당사자 연혁 [S3]'],
['2010','Ardmore에서 Cokonyx 제조가 이루어졌다는 법원 사실관계.','확인: 역사적 활동 [S20]'],
['2011-02-02','Carbonyx International USA, Inc.의 Form D. 발행인이 Delaware 설립 연도를 2010년으로 기재.','확인: 제출 내용 [S10]'],
['2013-11-21','WV Commerce 배포문이 Millwood 공장 계획을 발표.','확인: 계획 발표 [S12]'],
['2014 / FY2015','주 의회 기록과 예산 문서에 Carbonyx 투자가 등장. 최초 발표일로 쓰지 않음.','확인: 정부 기록 [S2][S11]'],
['2017-04-24','GFEZ 연혁에 Carbonyx International 투자협약.','확인: 투자 활동 [S18]'],
['2019-01-31','과거 carbonyx.com 아카이브에서 CASP·Cokonyx와 Plano·Ardmore 소개.','부분: 회사 설명 [S5]'],
['2021-06 / 08','Carbonyx Inc. 파산 사건 제출문서와 계획 확인명령 복제문.','확인 범위 제한 [S6][S13]'],
['2022-06 / 07','경매업체 기고와 업계 기사가 Millwood 미가동·공매를 서술.','부분: 날짜 상충 [S14][S15]'],
['2024-03-19','CBNX ASIA가 Carbonyx의 아시아 JV 파트너라는 아카이브.','확인: 당시 주장 [S7][S19]'],
['2026-10-04','CBNX의 현행 관계 설명과 Carbonyx Minerals의 현행 도메인을 구별해 열람.','확인: 관찰 시점 [S1][S16]']
];
pages.push(`<p class="kicker">시계열</p><h2>설립 설명에서 현재 도메인까지</h2>${table(['시점','공개 기록','근거의 범위'],chronology)}${figure('timeline','공개 기록의 주요 시점','그림: 출처에 명시된 사건 시점의 요약. 설립 연도는 당사자 설명이며, 발표는 실제 가동과 다르다. [S3][S12][S15][S16][S18][S20]')}`);
pages.push(`<p class="kicker">주제별 근거와 상충</p><h2>실제 활동과 홍보를 구분한다</h2><h3>Ardmore 제조는 역사적 근거가 있다</h3><p>Oklahoma 연방법원 의견은 Ardmore 시설과 Cokonyx 제조공정을 다루며 과거 제조 활동을 뒷받침한다. 이는 사업에 제조 실체가 전혀 없었다는 해석을 지지하지 않는다. 다만 해당 시점과 장소의 사실관계를 현재 CBNX의 생산능력, 계약 실적 또는 특허 권리로 확장할 수는 없다. [S9][S20]</p><h3>투자협약은 확인, 소유는 미확인</h3><p>GFEZ 정부 연혁의 투자협약은 CBNX ASIA 활동 소개에 나타나는 한국 투자 협의의 맥락과 부합한다. 정부 기록에 나타난 당사자 명칭은 Carbonyx International이다. 이 기록은 한국 투자 활동의 독립 근거이며 CBNX ASIA의 지분이나 사업 자산 소유를 증명하지 않는다. [S1][S18]</p><h3>Millwood는 발표와 결과를 나눠 읽는다</h3><p>WV Commerce 발표문은 공장 계획을 알렸고 이후 정부 기록에도 투자가 언급됐다. 반면 Iron Auction Group 기고는 설비를 “new/never fired”라고 표현하며 공매를 예고한다. 따라서 정부 발표를 상업 가동의 증거로 인용하는 것은 부적절하다. 경매업체는 설비 처분을 홍보하는 이해관계가 있는 출처이므로 기사 내용과 공매 완료 사실 역시 구별했다. [S2][S11][S12][S15]</p>${table(['상충 또는 오인','채택한 처리'],[
['최초 발표가 2014년이라는 해석','2013-11-21 주정부 배포문이 앞선다. 2014년은 후속 의회 기록으로 정정. [S11][S12]'],
['투자 발표를 실제 가동으로 해석','경매업체의 미가동 설명을 함께 제시. 생산량·매출·연속 가동은 확인 불가. [S12][S15]'],
['건설 연혁·공매 일정 차이','업계 자료 사이의 세부 날짜 차이를 해소하지 못했다. 준공일·낙찰 완료일을 확정하지 않음. [S14][S15]'],
['파산 재조직을 CBNX 승계로 해석','확인명령 복제문은 CBNX 승계 연결을 제공하지 않는다. 양도 문서 확인까지 보류. [S6][S13]'],
['현재 도메인을 역사적 회사로 해석','현재 Minerals 소개와 역사적 아카이브를 분리. [S5][S16][S17]']])}<p class="note">교정 기록: 정부 발표 시점, 제조 장소, 법인명, 도메인 관찰 시점을 분리했다. 보도에 제시된 대출 규모와 건설·공매 세부 일정은 확정 수치로 전재하지 않았다. [S12][S14][S15]</p>`);
pages.push(`<p class="kicker">미해결 부록과 조사 방법</p><h2>추가 문서가 필요한 질문</h2>${table(['미확인 주장','판정을 바꿀 자료'],[
['CBNX GROUP LLC의 법적 후신 관계','설립·상호 변경 증서, 합병·전환 기록, 양수도 계약. 같은 이름이나 인물만으로 충족되지 않음. [S3][S10][S13]'],
['CBNX ASIA의 독점권·JV 범위','서명 계약, 지역·제품 범위, 유효기간, 해지 여부, 합작법인 등록 및 주주명부. [S1][S7]'],
['CASP 특허의 현재 소유·라이선스','특허별 등록번호와 양도 이력, 라이선스 계약 및 파산계획의 대응 자산 목록. [S3][S13]'],
['Millwood의 상세 사업 결과','공식 가동·환경 기록, 처분 공고와 낙찰 결과, 공적 대출·회수 원장. 기사만으로 금액이나 완료일을 확정하지 않음. [S14][S15]'],
['한국 투자협약의 실제 이행','협약 원문과 변경·종료 기록, 후속 인허가, 토지·공장·투자 이행 자료. [S18]']])}<h2>방법과 한계</h2><p>공식 회사 페이지, 아카이브, 법원 의견과 제출문서, 정부 연혁·발표, SEC 공시 및 업계 기사를 대조했다. 관찰일과 문서가 다루는 사건일을 분리하고, 당사자 사이트의 여러 페이지와 같은 문서의 복제본은 독립 근거로 중복 계산하지 않았다. [S1][S3][S7][S9][S10][S18][S20]</p><p>등록·파산 자료 탐색과 Millwood 구현 상태를 별도 검토했다. 후신 관계와 대출·공매 상세는 공개 근거의 한계가 남아 미해결 부록에 유지했다. 법원 문서도 소송 당사자의 주장, 사실관계 요약, 주문의 효력을 구분해야 한다. [S6][S8][S13][S14][S15]</p><p>조사 기록 기준 연구 구성원 3명과 책임자 1명이 자료를 대조했다. 초기 탐색 뒤 확장과 반증 검토를 진행했고, 한정 조사 2건과 반증 검토 1회를 기록했다. 실행 코드로 법적 사실을 입증한 검증은 0건이다. 이 수치는 연구 수행 기록이며 사업 실적 수치가 아니다.</p><h3>검증 범위</h3><p>자료 수집의 기준일은 2026-10-04이다. 회사의 현재 등록 상태, 계약 원본, 특허별 권리 사슬 또는 재무제표에 대한 보증 업무는 수행하지 않았다. 불리한 보도의 존재는 확인했지만, 근거를 확보하지 못한 금액·세부 일자는 사실로 승격하지 않았다. [S3][S10][S14][S15]</p><p class="note">출처 목록에는 조사에서 사용한 모든 항목을 유지한다. 동일 URL인 [S7]과 [S19], 같은 법원 의견인 [S9]와 [S20]은 서로 다른 독립 증거가 아니다. [S4]의 확인 경로는 [S18] 정부 페이지로 보완했다.</p>`);
for (let offset=0;offset<sources.length;offset+=10) pages.push(`<p class="kicker">번호 출처 · 전체 열람일 2026-10-04</p><h2>${offset?'출처 목록 계속':'출처 목록'}</h2><p class="note">URL은 원문 추적용이다. 회사 자체 주장·공식 기록·보도 자료의 증거 수준은 본문에서 구분했다. 출처 번호는 조사 장부와 같다.</p><div class="sources">${sources.slice(offset,offset+10).map(s=>`<div class="source" id="S${s.id}"><p><strong>[S${s.id}]</strong> ${esc(s.description.replaceAll('—',':').replaceAll('독립 확인 진행 중.','보도된 주장, 확정 근거로 사용하지 않음.').replaceAll('렌더링 검증 진행 중.','정부 페이지 [S18]로 보완.'))}</p><a href="${esc(s.url)}">${esc(s.url)}</a><p class="access">접근일: 2026-10-04</p></div>`).join('')}</div>`);
const css=`@page{size:A4;margin:18mm} :root{--ink:#17212B;--paper:#F8F7F3;--accent:#0B6E69;--rule:#D6D3CA;--muted:#5D6770;--body:9.5pt;--small:8pt;--gap:6mm}*{box-sizing:border-box}html{font-family:'Noto Sans CJK KR','Noto Sans KR',sans-serif;color:var(--ink);background:var(--paper)}body{margin:0;font-size:var(--body);line-height:1.65;word-break:keep-all;overflow-wrap:anywhere}main{max-width:174mm;margin:auto}.page{break-after:page}.page:last-child{break-after:auto}h1{font-size:25pt;line-height:1.3;letter-spacing:-.035em;margin:6mm 0 8mm}h2{font-size:17pt;line-height:1.4;color:var(--accent);margin:0 0 6mm;break-after:avoid}h3{font-size:11pt;line-height:1.5;margin:5mm 0 2mm;break-after:avoid}p{margin:0 0 3mm;orphans:3;widows:3}.kicker{color:var(--muted);font-size:var(--small);border-bottom:1px solid var(--rule);padding-bottom:3mm;margin-bottom:7mm}.lead{font-size:15pt;line-height:1.6;margin-bottom:7mm;font-weight:600}table{width:100%;border-collapse:collapse;font-size:8.6pt;margin:4mm 0 6mm;table-layout:fixed}th{text-align:left;background:var(--paper);color:var(--accent);font-weight:700}th,td{padding:2.5mm 3mm;border-bottom:1px solid var(--rule);vertical-align:top}th:first-child,td:first-child{width:27%}tr{break-inside:avoid}thead{display:table-header-group}.note,figcaption{font-size:var(--small);color:var(--muted);line-height:1.6}figure{margin:4mm 0 6mm;break-inside:avoid}.figure-frame{height:91mm;border:1px solid var(--rule);background:var(--paper);padding:3mm}.figure-frame img{width:100%;height:100%;object-fit:contain}figcaption{margin-top:2mm}.page:nth-child(3) .figure-frame{height:66mm}.page:nth-child(3) table{font-size:8pt}.page:nth-child(3) td{padding:1.8mm 2mm}.page:nth-child(3) td:first-child{width:20%}.sources{font-size:var(--small)}.source{margin:0 0 4mm;break-inside:avoid}.source p{margin:0}.source a{font-size:7.3pt;color:var(--accent);overflow-wrap:anywhere;word-break:break-all}.access{color:var(--muted);font-size:7pt}a{color:var(--accent)}@media screen{body{padding:24px}.page{padding:8mm 0;margin-bottom:15mm;border-bottom:1px solid var(--rule)}}@media print{html{print-color-adjust:exact;-webkit-print-color-adjust:exact}}`;
const refinements = `.page:nth-child(3) th:first-child,.page:nth-child(3) td:first-child{width:17%}.page:nth-child(3) th:last-child,.page:nth-child(3) td:last-child{width:25%}@page{@bottom-center{content:counter(page);font-family:'Noto Sans CJK KR',sans-serif;font-size:8pt;color:#5D6770}}`;
const html=`<!doctype html>\n<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="CBNX와 Carbonyx의 공개자료상 관계, 연혁과 미해결 쟁점"><title>CBNX와 Carbonyx 공개자료 실사</title><style>${css}${refinements}</style></head><body><main>${pages.map(p=>`<section class="page">${p}</section>`).join('\n')}</main></body></html>`;
fs.writeFileSync(path.join(dir,'report.html'),html);
const text=pages.map(p=>p.replace(/<img[^>]*>/g,'').replace(/<\/t[dh]>/g,' | ').replace(/<\/tr>/g,'\n').replace(/<[^>]+>/g,'\n').replace(/\n{3,}/g,'\n\n')).join('\n\n');
fs.writeFileSync(path.join(dir,'SYNTHESIS.md'),`# CBNX와 Carbonyx 조사 종합\n\n기준일: 2026-10-04. 출처 장부 ${sources.length}항목. 법적 동일성 미확인 주장은 부록에 분리했다.\n\n${text}\n\n## 조사 산출물 연결\n\n주장 판정: claim-graph.md. 관찰 단위: observation-manifest.md. 확장: expansion-log.md. 한정 조사: excursion-log.md. 인쇄 원본: report.html.\n`);
console.log(JSON.stringify({sources:sources.length,domains:new Set(sources.map(s=>new URL(s.url).hostname)).size,sections:pages.length,assets:['assets/timeline.svg','assets/relationship.svg']},null,2));
